### ISSUE TITLE
Loading a media randomly leads to a timeout issue

### ISSUE THREAD

**Issue by ghost** [Tapanila/SharpCaster#121]
I use the following flow and latest branch (**refactoring**) :
          
    var chromecast = await TestHelper.FindChromecast();
    var client = new ChromecastClient();
    await client.ConnectChromecast(chromecast);

    var status = await client.LaunchApplicationAsync("B3419EF5");

    var media = new Media
    {
        ContentUrl = "https://commondatastorage.googleapis.com/gtv-videos-bucket/CastVideos/mp4/DesigningForGoogleCast.mp4"
    };

    var mediaStatus = await client.GetChannel<IMediaChannel>().LoadAsync(media);

Most of the time, the application "SharpCaster Demo Receiver" launch successfully, but calling LoadAsync(media) leads to a timeout issue 90% of the time (thrown by TimeoutAfter<T> method).

Btw, the unit test TestLoadingMedia fails (timeout issue) and the test ConnectToChromecastAndLaunchApplicationTwice fails because both LaunchTransportId are same.

**Comment by Tapanila** [comment]
Load media is not really failing because of a timeout issue. It's failing since Chromecast responds with "Close" message and the current logic doesn't handle that message and just responds to timeout.
So there is something wrong on the logic that sends the Load Media and the strange thing here is that Chromecast sometimes accepts it.

Will need to check ConnectToChromecastAndLaunchApplicationTwice test, since it should be working. Might be that I have broken it or the test case is not stable enough. The test cases will cover all of the use cases of the SDK and will be used to verify the stability of SDK.

The refactoring branch is still "Work In Progress" and I wouldn't recommend using it currently. It is still missing some features and the MediaChannel still has quite a lot of problems. Also, it will still have a lot of changes before I land it into Dev and later to Master.
