### ISSUE TITLE
Attempting to cast Urls

### ISSUE THREAD

**Issue by 4saknhero** [Tapanila/SharpCaster#122]
So I changed the controller type to WebController, changed the action to LaunchWeb in both the Connected and MediaStatusChange methods, then commented out the LoadMedia and typed up 

`await _controller.LoadUrl("https://youtube.com");`

Below is the stack Trace from the console, what am I missing? (Complete novice at this!)

```
Received: PONG
PONG
Received: RECEIVER_STATUS
Exception thrown: 'Newtonsoft.Json.JsonReaderException' in Newtonsoft.Json.dll
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: o. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value)
   at Extensions.Api.CastChannel.CastMessage.GetJsonType() in C:\Users\Kevin.HUGHSTON\Downloads\SharpCaster-master\SharpCaster-master\SharpCaster\Models\CastMessage.cs:line 42
   at SharpCaster.ChromeCastClient.<ReadPacket>d__59.MoveNext() in C:\Users\Kevin.HUGHSTON\Downloads\SharpCaster-master\SharpCaster-master\SharpCaster\ChromeCastClient.cs:line 200
```

**Comment by Tapanila** [comment]
I will look into this on a weekend.

**Comment by ChristopheCuddlup** [comment]
Hi,

I could not make it work either.

Here is my code taken from the test class:

        WebController _webController = null;
        public async Task OpenWebPage()
        {
            _webController = await _chromecastService.ChromeCastClient.LaunchWeb();
            await Task.Delay(5000);
(1)->    await _webController.LoadUrl("https://www.windytv.com/");
            await Task.Delay(5000);
        }

        public async Task CloseWebPageController()
        {
            if (_webController != null)
            {
(2)->        await _webController.StopApplication();
            }
        }

Connection works ok, but  Web page does not show up (white screen). In both (1) and (2),
sottware raises an exception that translated to english would be something like:

Input/output operation has been abandonned due to thread stop or upon application request (Exception from HRESULT 0x800703E3)
in ChromecastSocketService.Write().

Any help would be greatly appreciated.
Thanks a lot
Christophe

**Comment by ChristopheCuddlup** [comment]
Hi,

I am sorry to bother all of you again, pleaselet me know where to publish such question if here is ot the right place. Thank you.
I am still struggling making a web page opened on my TV. Basically, I have an IIS Server on my computer, a Chromeccast and TV attached to it. I wan't one HTML Page hosted on my IIS-Server, to be displayed on the TV (well actually several TVs).
I have registered my Chromecast for development. Looks ok since I can see the video with the UWP sample code (even though I can't connect in debug mode to the chromescast : it is listed in the chrome://inspect page, but no link is attached to it (port issue?)).
I have stopped my firewall and Antivirus.
Question: do I need to register an app ID to google ? If so which type? Looks to me I am running a sender app, not a custom receiver one.
Should I then change the app ID in the WebController class?

Thanks a lot for your help.
Christophe

**Comment by Tapanila** [comment]
This is a right place to ask questions and I try to answer them. Sometimes I'm just not able to do it for some other reasons but trying to allocate more time to this project currently. 

Really sorry for really long response time and for not looking into this problem.

Debug mode:
Both the application and device must be registered with the same google account in order for you to perform debugging.
https://developers.google.com/cast/docs/debugging

Registering application:
Register it as "Styled Custom Receiver"

**Comment by ChristopheCuddlup** [comment]
Thank you. I will try asap.

**Comment by ChristopheCuddlup** [comment]
Hi,
I used the Styled Custom Receiver app id, double checked my chromecast serial number in the google Cast SDK Developer Console. Still, I receive a CLOSE message after the call to:
         _webController = await _chromecastService.ChromeCastClient.LaunchWeb();
I can see the my chromecast in the inspect page, but have never seen the link to attach to it. I need to try this again with the default video playing app.
Am I right to consider the C# code a sender app?
Thanks and regards
Christophe

**Comment by ChristopheCuddlup** [comment]
Hi,

I finally found a way to display my local web site HTML page using a custom renderer.

For the others looking for a similar solution, here are some details:
Sender is Sharpcast with custom renderer app ID in WebController.
Custom renderer page is stored on an Internet-accessible HTTPS server.
Then the custom renderer displays my local web server page.
More details here: https://stackoverflow.com/a/21961503/6190527
By the way, I have a ChromeCastUltra and debugging worked for me only when removed the guest mode from the google SDK console for the application.

Thanks for the help
Best regards
Christophe
